<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DTWD24" name="gpmsUI.gpmsAutomation.addingNewDetails" tests="10" failures="2" timestamp="25 Apr 2019 14:38:05 GMT" time="66.848" errors="0">
  <testcase name="createPayrollAssignment" time="6.887" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
  <testcase name="addDeductionsRandom" time="9.597" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
  <testcase name="addPayroll" time="1.875" classname="gpmsUI.gpmsAutomation.addingNewDetails">
    <failure type="java.lang.AssertionError" message="Failed Add Payoll step, as  Payoll Name &#039;Test Payroll Apr10&#039; already exists">
      <![CDATA[java.lang.AssertionError: Failed Add Payoll step, as  Payoll Name 'Test Payroll Apr10' already exists
at org.testng.Assert.fail(Assert.java:96)
at gpmsUI.gpmsAutomation.addingNewDetails.addPayroll(addingNewDetails.java:172)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addPayroll -->
  <testcase name="addEmployee" time="4.376" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
  <testcase name="addEntitlementsPermRandom" time="9.580" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
  <testcase name="editPayrollPeriods" time="3.126" classname="gpmsUI.gpmsAutomation.addingNewDetails">
    <failure type="java.lang.AssertionError" message="Failed: Payroll periods of given Payroll Year already exits">
      <![CDATA[java.lang.AssertionError: Failed: Payroll periods of given Payroll Year already exits
at org.testng.Assert.fail(Assert.java:96)
at reusableMethods.commonMethods.editPeriods(commonMethods.java:54)
at gpmsUI.gpmsAutomation.addingNewDetails.editPayrollPeriods(addingNewDetails.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- editPayrollPeriods -->
  <testcase name="addPaymentsRandom" time="9.666" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
  <testcase name="addUnitPayRandom" time="8.382" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
  <testcase name="addEntitlementsUnitPayRandom" time="8.649" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
  <testcase name="addEntitlementsTempRandom" time="4.710" classname="gpmsUI.gpmsAutomation.addingNewDetails"/>
</testsuite> <!-- gpmsUI.gpmsAutomation.addingNewDetails -->
